export const projects = [
  {
    title: 'Chat Messenger App',
    description: "Aplicacion de chat que permite proceso de autenticacion y registro de usuarios a traves de Next Auth.",
    image: '/images/chat.jpeg',
    tags: ['Mongo', 'Tailwind css', 'Next js', 'Node'],
    source: 'https://nextjs-chat-app-liart.vercel.app/',
    visit: 'https://github.com/Leon2192/nextjs-chat-app',
    id: 0,
  },
  {
    title: 'Spotify UI Clone',
    description: "Clon de la interfaz de Spotify, desarrollado con Next js y Tailwind CSS.",
    image: '/images/spotify.png',
    tags: ['Next js', 'Tailwind CSS', 'React js'],
    source: 'https://spotify-ui-clone-six.vercel.app/',
    visit: 'https://github.com/Leon2192/spotifyUI-clone',
    id: 1,
  },
  {
    title: 'Netflix Clone',
    description: "Clon de aplicacion Netflix, implementando autenticacion a traves de Next Auth y data fetching con TMDB(Api).",
    image: '/images/netflix.png',
    tags: ['React', 'Next js', 'Tailwind CSS', 'Mongo'],
    source: 'https://netflix-clone-tailwind-nextjs.vercel.app/auth',
    visit: 'https://github.com/Leon2192/netflix-clone-tailwind-nextjs',
    id: 2,
  },
  {
    title: 'Openjira',
    description: "Aplicacion de administracion de tareas desarrollada para cliente RL-ARQ estudio. Drag & drop y crud para generar nuevas tareas, editarlas y eliminarlas.",
    image: '/images/jira.png',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://openjira-blue.vercel.app/',
    visit: 'https://github.com/Leon2192/openjira',
    id: 3,
  },
  {
    title: 'PokeFetch',
    description: "Aplicacion desarrollada con HTML, CSS y Javascript, y data fetching a Pokeapi (Api).",
    image: '/images/poke.png',
    tags: ['Html', 'Css', 'Javascript'],
    source: 'https://poke-challenge-rust.vercel.app/',
    visit: 'https://github.com/Leon2192/pokeChallenge',
    id: 3,
  },
  {
    title: 'Go pro',
    description: "Desarrollo de reseller de la marca Go Pro desarrollado con las tecnologias React js, Next Js y tailwind css.",
    image: '/images/gopro.png',
    tags: ['React', 'Next js', 'Tailwind CSS'],
    source: 'https://gopro-landing-page.vercel.app/',
    visit: 'https://github.com/Leon2192/gopro-landing-page',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];